timer: 30 #how long each map lasts.
spawn: #where players will teleport when the map resets.
  world: "world"
  x: 0.0
  y: 80.0
  z: 0.0
  pitch: 0.0
  yaw: 90.0
placeholders:
  prefix: "map"
enabled:
  Map1:
    spawn:
      world:
      x: 0
      y: 65
      z: 0
      pitch: 0.0
      yaw: 90.0
  Map2:
    spawn:
      world:
      x: 0
      y: 65
      z: 0
      pitch: 0.0
      yaw: 90.0
  Map3:
    spawn:
      world:
      x: 0
      y: 65
      z: 0
      pitch: 0.0
      yaw: 90.0